version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - DOCKER_LOGIN=`aws ecr get-login --no-include-email --region us-east-2`
      - $DOCKER_LOGIN
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t nginx-test:latest .
      - docker tag nginx-test:latest 266902911314.dkr.ecr.us-east-2.amazonaws.com/nginx-test:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 266902911314.dkr.ecr.us-east-2.amazonaws.com/nginx-test:latest
